DROP TABLE IF EXISTS AppartientA;
DROP TABLE IF EXISTS Equipes;
DROP TABLE IF EXISTS Sportifs;
DROP TABLE IF EXISTS AdherentEpreuves;
DROP TABLE IF EXISTS ResultatG;
DROP TABLE IF EXISTS Adherent;
DROP TABLE IF EXISTS Epreuves;
DROP TABLE IF EXISTS Disciplines;